apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-multi
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job-multi
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job