apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - image: edgarsang/kubia-unhealthy
      name: kubia
      ports:
        - containerPort: 28080
      livenessProbe:
      httpGet:
        path: /
        port: 28080