apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume
spec:
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /etc/nginx/conf.d  #컨피그맵 볼륨을 마운트 하는 위치
          name: config
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: fortune-config        # 이 볼륨은 fortune-config 컨피그맵을 참조한다
        defaultMode: 6600         # 모든 파일 권한을 -rw-rw-----로 설정

