apiVersion: v1
kind: Pod
metadata:
  name: fortune2s
spec:
  containers:
  - image: edgarsang/fortune:args
    env:
      - name: INTERVAL
    name: html-generator
    volumeMounts:
      - mountPath: /var/htdocs
        name: html
