apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
    - name: main
      image: tutum/curl
      command: ["sleep", "9999999"]
      resources:
        requests:
          cpu: 15m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
