apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      app: kubia
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: nodejs
          image: luksa/kubia:v3
          readinessProbe:
            periodSeconds: 1      #1초마다 실행될 레디니스 프로브정의
            httpGet:
              port: 8080
              path: /             #Http get 요청을 수행한
